language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master
    - develop

before_script:
  - sudo apt-get update
  - sudo apt-get install php5-fpm
  - composer self-update
  - composer install --dev --prefer-source --no-interaction --no-progress

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
