<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir))).'/default/files/composer';

return array(
    'Satooshi\\Component' => array($vendorDir . '/satooshi/php-coveralls/src'),
    'Satooshi\\Bundle' => array($vendorDir . '/satooshi/php-coveralls/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'PHPMD\\' => array($vendorDir . '/phpmd/phpmd/src/main/php'),
    'PDepend\\' => array($vendorDir . '/pdepend/pdepend/src/main/php'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
);
